
spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5438/postgres"
    username: postgres
    password: postgres
server:
  error:
    include-message: always
  servlet:
    session:
      cookie:
        http-only: false
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG